# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="mb_commander"
version="${file.jarVersion}"
displayName="Mine & Blade: Commander"
credits="The Forge dev team"
authors="Rastersaurus Rex"
description='''
Live out your minecraft battle commander fantacies
'''
[[dependencies.mb_commander]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mb_commander]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
